import { Geist, Geist_Mono, Akatab, Fira_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const Akatabs = Akatab({
  variable: "--font-akatab",
  subsets: ["latin"],
  weight: "400",
});
const FiraMonos = Fira_Mono({
  variable: "--font-fira-mono",
  subsets: ["latin"],
  weight: "400",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${Akatabs.variable} ${FiraMonos.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
